env:
  - NG_CLI_ANALYTICS=false
language: node_js
node_js:
  - "12"
script:
  - npm run lint
  - npm run build:lib
  - npm run build
  - xvfb-run npm run cy:ci
services:
  - xvfb
before_script:
  - npm ci
notifications:
  webhooks:
  - https://www.travisbuddy.com/
  email: false
sudo: required
addons:
  chrome: stable
cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
    - ~/.cache/Cypress
