env:
  - NG_CLI_ANALYTICS=false
dist: xenial
language: node_js
node_js:
  - "12"
script:
  - npm run lint
  - npm run build:lib
  - npm run build
  - npm run cy:ci
install:
  - npm ci
notifications:
  webhooks:
  - https://www.travisbuddy.com/
  email: false
sudo: required
services:
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
    - ~/.cache/Cypress
