env:
  - NG_CLI_ANALYTICS=false
language: node_js
node_js:
  - "12"
script:
  - npm run lint
  - npm run build:lib
  - npm run build
  - npm run cy:ci
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
notifications:
  webhooks:
  - https://www.travisbuddy.com/
  email: false
sudo: required
addons:
  chrome: stable
cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
